TITLE: ESS245 Loops 2

## Some pointers for the Loops 2 Assignment.

### Creating a markdown table

Markdown tables follow a very simple scheme and are defined in the following way:

    |     CO2 |    Temp |
    | ------- | ------- |
    |     280 |      18 |
    |     300 |      19 |
    |     410 |      20 |

e.g., the vertical bars separate the columns, and the horizontal lines are created by adding dashes. Note the dashed do not need to align with the header text. I typically only use 3.

It is best, to first use the print function to test your output. However, once all the characters are in place, you can direct python to output your table not as text, but as markdown that will be rendered by your notebook. In the following, I manually build the output string and then output it as text:

In [1]:
a = """
| **CO2** |    **Temp** |
| ------- | ------- |
|     280 |      18 |
|     300 |      19 |
"""
print(a)

Now I add a special command which renders the output as markdown

In [1]:
from IPython.display import display_markdown

a = """
| **Hello** | **World** |
| --- | --- |
| 280 | 18  | 
| 300 | 19  | 
| 410 | 20  |
"""
display_markdown(a, raw=True)

## Stop Reading Here!

**If you are a bit more advanced, and look for a good challenge, do not read any further!** If you struggle with the advanced question, feel free to return here.

### Looping over a dictionary

The `items()` method will return both the key and the value.

In [1]:
d = {"A": 12, "B": 0}

for key, value in d.items():
    print(f"key = {key}, value = {value}")

print(list(d.items()))

### Dictionary to Table

The following examples provides some pointers on how to convert the dictionary `d` into a table:

#### What do we know

-   `d` is a dict where each key points to another dictionary `colx`
-   We know that `colx` is a dictionary with two keys, `'header'` and `'value'`
-   We know that the `'header'` value is a string
-   We know that the `'values'`  value is a list
-   We do not know how many columns are in dictionary `d`
-   We do not know how many values are in the `colx['values']`

In [1]:
d = {
    "col1": {
        "header": "CO_2",
        "values": [280, 300, 410],
    },
    "col2": {
        "header": "Temp",
        "values": [18, 19, 20],
    },
}

#### What do we need to do?

-   Loop over `d` to find out how many columns there are
-   For each column, extract the header string
-   For each column extract the value list

#### Why is this confusing

-   Because you need to loop over the values list **and** the columns!
-   Extracting the header row requires a different loop, then extracting the values

#### Plan of attack

-   Think of it as rows of text
-   First extract the column headers
-   Then extract each row
-   It is best to build your output string one line at a time.